# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseset',
            old_name='user',
            new_name='profile',
        ),
    ]
