# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushup', '0003_auto_20170625_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('pushup', 'Push Up'), ('situp', 'Sit-up')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='repetitions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
